name: therapy_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-4.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  get: any
  table_calendar: ^3.0.9
  flutter_dotenv: ^5.1.0
  iconly:
  flutter_spinkit: ^5.2.0
  fluttertoast: any
  readmore: ^2.2.0
  badges: ^3.1.2
  upgrader: ^8.1.0
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env  
